import type { Metadata } from "next";
import { Square_Peg, Montserrat, League_Spartan } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/common/Navbar/Navbar";

const squarePeg = Square_Peg({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-decorative",
});

const montserrat = Montserrat({
  variable: "--font-body",
  subsets: ["latin"],
});

const leagueSpartan = League_Spartan({
  variable: "--font-heading",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${squarePeg.variable} ${montserrat.variable} ${leagueSpartan.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
